![walmartecomm](walmartecomm.jpg)

Walmart is the biggest retail store in the United States. Just like others, they have been expanding their e-commerce part of the business. By the end of 2022, e-commerce represented a roaring $80 billion in sales, which is 13% of total sales of Walmart. One of the main factors that affects their sales is public holidays, like the Super Bowl, Labour Day, Thanksgiving, and Christmas. 

In this project, you have been tasked with creating a data pipeline for the analysis of supply and demand around the holidays, along with conducting a preliminary analysis of the data. You will be working with two data sources: grocery sales and complementary data. You have been provided with the `grocery_sales` table in `PostgreSQL` database with the following features:

# `grocery_sales`
- `"index"` - unique ID of the row
- `"Store_ID"` - the store number
- `"Date"` - the week of sales
- `"Weekly_Sales"` - sales for the given store

Also, you have the `extra_data.parquet` file that contains complementary data:

# `extra_data.parquet`
- `"IsHoliday"` - Whether the week contains a public holiday - 1 if yes, 0 if no.
- `"Temperature"` - Temperature on the day of sale
- `"Fuel_Price"` - Cost of fuel in the region
- `"CPI"` – Prevailing consumer price index
- `"Unemployment"` - The prevailing unemployment rate
- `"MarkDown1"`, `"MarkDown2"`, `"MarkDown3"`, `"MarkDown4"` - number of promotional markdowns
- `"Dept"` - Department Number in each store
- `"Size"` - size of the store
- `"Type"` - type of the store (depends on `Size` column)

You will need to merge those files and perform some data manipulations. The transformed DataFrame can then be stored as the `clean_data` variable containing the following columns:
- `"Store_ID"`
- `"Month"`
- `"Dept"`
- `"IsHoliday"`
- `"Weekly_Sales"`
- `"CPI"`
- "`"Unemployment"`"

After merging and cleaning the data, you will have to analyze monthly sales of Walmart and store the results of your analysis as the `agg_data` variable that should look like:

|  Month | Weekly_Sales  | 
|---|---|
| 1.0  |  33174.178494 |
|  2.0 |  34333.326579 |
|  ... | ...  |  

Finally, you should save the `clean_data` and `agg_data` as the csv files.

It is recommended to use `pandas` for this project.

In [2]:
-- Write your SQL query here
SELECT * FROM grocery_sales

Error: Failed to execute query: Response not ok: status 500, body: Internal Server Error

In [3]:
import pandas as pd
import os

extra_df = pd.read_parquet("extra_data.parquet")
extra_df.head()

   index  IsHoliday  Temperature  ...  Unemployment  Type      Size
0      0          0        42.31  ...         8.106   3.0  151315.0
1      1          0        42.31  ...         8.106   3.0  151315.0
2      2          0        42.31  ...         8.106   3.0  151315.0
3      3          0        42.31  ...           NaN   3.0  151315.0
4      4          0        42.31  ...           NaN   3.0  151315.0

[5 rows x 13 columns]

In [44]:
import pandas as pd
import os

# Extract function is already implemented for you 
def extract(store_data, extra_data):
    extra_df = pd.read_parquet(extra_data)
    merged_df = store_data.merge(extra_df, on = "index")
    return merged_df

# Call the extract() function and store it as the "merged_df" variable
merged_df = extract(grocery_sales, "extra_data.parquet")

In [38]:
merged_df.head()

   index  Store_ID       Date  Dept  ...         CPI  Unemployment  Type      Size
0      0         1 2010-02-05     1  ...  211.096358         8.106   3.0  151315.0
1      1         1 2010-02-05    26  ...  211.096358         8.106   3.0  151315.0
2      2         1 2010-02-05    17  ...  211.096358         8.106   3.0  151315.0
3      3         1 2010-02-05    45  ...  211.096358           NaN   3.0  151315.0
4      4         1 2010-02-05    28  ...  211.096358           NaN   3.0  151315.0

[5 rows x 17 columns]

In [45]:
merged_df.isna().sum()

index            0
Store_ID         0
Date            39
Dept             0
Weekly_Sales    38
IsHoliday        0
Temperature      0
Fuel_Price       0
MarkDown1        0
MarkDown2        0
MarkDown3        0
MarkDown4        1
MarkDown5        1
CPI             47
Unemployment    37
Type             1
Size             1
dtype: int64

In [46]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 231522 entries, 0 to 231521
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   index         231522 non-null  int64
 1   Store_ID      231522 non-null  int64
 2   Date          231483 non-null  datetime64[ns]
 3   Dept          231522 non-null  int64
 4   Weekly_Sales  231484 non-null  float64
 5   IsHoliday     231522 non-null  int64
 6   Temperature   231522 non-null  float64
 7   Fuel_Price    231522 non-null  float64
 8   MarkDown1     231522 non-null  float64
 9   MarkDown2     231522 non-null  float64
 10  MarkDown3     231522 non-null  float64
 11  MarkDown4     231521 non-null  float64
 12  MarkDown5     231521 non-null  float64
 13  CPI           231475 non-null  float64
 14  Unemployment  231485 non-null  float64
 15  Type          231521 non-null  float64
 16  Size          231521 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(4)
memory usage: 31.8 MB

In [47]:
# Create the transform() function with one parameter: "raw_data"
cols = ["Store_ID","Month","Dept","IsHoliday","Weekly_Sales","CPI","Unemployment"]
isnumber = [col for col in merged_df if pd.api.types.is_numeric_dtype(merged_df[col])]
def transform(raw_data):
    raw_data[isnumber] = raw_data[isnumber].fillna(0)
    raw_data["Month"] = raw_data['Date'].dt.month
    raw_data = row_data[row_data['Weekly_Sales'] > 10000]
    raw_data = row_data[cols]
    return raw_data

In [49]:
# Call the transform() function and pass the merged DataFrame
clean_data = transform(merged_df)

In [51]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106193 entries, 0 to 231519
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   index         106193 non-null  int64
 1   Store_ID      106193 non-null  int64
 2   Date          106168 non-null  datetime64[ns]
 3   Dept          106193 non-null  int64
 4   Weekly_Sales  106193 non-null  float64
 5   IsHoliday     106193 non-null  int64
 6   Temperature   106193 non-null  float64
 7   Fuel_Price    106193 non-null  float64
 8   MarkDown1     106193 non-null  float64
 9   MarkDown2     106193 non-null  float64
 10  MarkDown3     106193 non-null  float64
 11  MarkDown4     106193 non-null  float64
 12  MarkDown5     106193 non-null  float64
 13  CPI           106193 non-null  float64
 14  Unemployment  106193 non-null  float64
 15  Type          106193 non-null  float64
 16  Size          106193 non-null  float64
 17  Month         106168 non-null  float64
dtypes: datetime64[ns](1), float64(13), int64(4)
memory usage: 15.4 MB

In [5]:
# Create the avg_weekly_sales_per_month function that takes in the cleaned data from the last step
def avg_weekly_sales_per_month(clean_data):
    # Write your code here
    pass

In [6]:
# Call the avg_weekly_sales_per_month() function and pass the cleaned DataFrame

In [7]:
# Create the load() function that takes in the cleaned DataFrame and the aggregated one with the paths where they are going to be stored
def load(full_data, full_data_file_path, agg_data, agg_data_file_path):
    # Write your code here
    pass

In [8]:
# Call the load() function and pass the cleaned and aggregated DataFrames with their paths

In [9]:
# Create the validation() function with one parameter: file_path - to check whether the previous function was correctly executed
def validation(file_path):
    # Write your code here
    pass

In [10]:
# Call the validation() function and pass first, the cleaned DataFrame path, and then the aggregated DataFrame path